### ISSUE TITLE
Checklist - Advanced Economy Bot

### ISSUE THREAD

**Issue by notsniped** [PyBotDevs/isobot#250]
### Advanced Economy Bot Ideas
I want to try to add these features to make isobot more like an economy bot than a jack-of-all-trades-master-at-nothing bot.

- [ ] Add taxes for specific items bought from the shop (for example, weapons)
- [ ] Add weapons to the shop
- [ ] Add command to kill members for coins and items
- [ ] Add real estate and vehicles (for net-worth)
- [ ] Make a levelling leaderboard for servers
- [ ] Make a net-worth leaderboard globally
- [ ] Add isobot subscriptions for access to beta and unreleased/removed commands
- [ ] Add different jobs to the `/work` command

*More ideas and features coming soon*
