### ISSUE TITLE
General Isobot Development Todo List (April-May 2024 Roadmap)

### ISSUE THREAD

**Issue by notsniped** [PyBotDevs/isobot#369]
- [x] Move help command into `/help list` and `/help info` (#370) 
    > Use `/help list` to show all available/usable commands in the bot, and to search for specific commands
    > Use `/help info` to display detailed descriptions and information on a specific command
- [x] Autosort all commands into different categories in `/help list` (#380)
- [x] Add warning system to bot (moderation commands) (#376)
- [x] Move all automod commands into a separate slash command category (#374)
- [x] Add server verification system in isobot (finally) (#387 LETS GOOOOOOO I DID IT)
- [x] ~~Rewrite all commands in osu cog and add back support for osu commands (make them WAY better)~~ (cancelled due to lack of necessity)
- [x] ~~Add a lot of custom emojis to the bot~~ (also cancelled due to lack of necessity)
- [x] Add back support for ChatGPT and DALL-E commands (#373)
- [x] Add autorole server command (add a role automatically to all server newjoiners) (#384)
- [x] ~~Add `/settings` slash commands to the bot to allow people to edit their general bot settings~~ (already done) (a long time ago)
- [x] Add some User Commands as slash command substitutes in the bot (#378)
- [x] Add `/serverinfo` to isobot (#381)
- [x] Move isocard database support commands to framework (yes, I AM still working on isocard, not just another dead unreleased feature) :) (#375)
- [x] Add some new commands to fun cog
    > Random number command (#382)
    > `/howgay` (#383)
- [x] ~~Add Urban Dictionary implementation~~ (cancelled due to lack of API resources)

### Web Updates
- [x] ~~#385~~ (moved to a new issue as not directly related to isobot client)

### Extras!
- [x] Add ability to send level-up messages in a specific server's channel instead of in user's DMs. (suggested by a Discord user in the NKA Network server 👍) (#386)

**Comment by notsniped** [comment]
All bot-related tasks in the Isobot April-May Feature Roadmap are finally completed!! :)
